name:                day11
version:             0.1.0.0
github:              matthewleon/day11
license:             BSD3
author:              Matthew Leon
maintainer:          ml@matthewleon.com
copyright:           2017 Matthew Leon

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/matthewleon/day11#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  day11-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day11

tests:
  day11-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day11
